version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
      
  flask-app:
    build: .
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DB_URI: ${DB_URI}
      OPENAI_API_KEY:  ${OPENAI_API_KEY}
    ports:
       - "5001:5001"
    depends_on:
      - db
    env_file: ".env"
    networks:
      - backend
networks:
  backend:
volumes:
  postgres_data:
