version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB}  -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  flask-app:
    build: .
    environment:
      DB_URI: ${DB_URI}
      OPENAI_API_KEY:  ${OPENAI_API_KEY}
    ports:
       - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    networks:
      - backend
networks:
  backend:
volumes:
  postgres_data:
